name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'
        cache: false

    - name: Environment information
      run: |
        go version
        go env
        pwd
        ls -la
        echo "GOPATH: $GOPATH"
        echo "GOROOT: $GOROOT"

    - name: Get dependencies
      run: |
        go mod tidy
        go mod download
        go mod verify
        go list -m all

    - name: Test model package
      run: go test -v ./pkg/model/...

    - name: Test crawler package
      continue-on-error: true
      run: |
        echo "Testing crawler package..."
        go test -v ./pkg/crawler/...
        echo "Test exit code: $?"

    - name: Test individual files
      run: |
        echo "Testing individual files..."
        for file in $(find . -name "*_test.go"); do
          echo "Testing $file..."
          go test -v $file || echo "Failed: $file"
        done
        
    - name: Generate coverage report
      continue-on-error: true
      run: |
        go test -coverprofile=coverage.out -covermode=atomic ./... || true
        go tool cover -func=coverage.out
        
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v3
      continue-on-error: true
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        
    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage.out 