name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'
        check-latest: true

    - name: Show Go version
      run: go version

    - name: Get dependencies
      run: |
        go mod tidy
        go mod download
        go mod verify

    - name: Run tests
      run: go test -v ./... || { echo "Tests failed"; exit 1; }

    - name: Run tests with race detector
      run: go test -race -v ./... || { echo "Race detector tests failed"; exit 1; }
      
    - name: Generate coverage report
      run: |
        go test -coverprofile=coverage.out -covermode=atomic ./...
        go tool cover -func=coverage.out
        
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        
    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage.out 